var varr = [
    {
      idproducto: 1,
      nombre: 'Camiseta tipo polo para dama',
      picture: camiseta_tipo_polo,
      precio_venta: 123,
      descripcion: 'Compra Protegida, recibe el producto que esperabas o te devolvemos tu dinero.',
      marca: 'Adidas',
      stock: 5,
    },
    {
      idproducto: 2,
      nombre: 'Camiseta atletico Madrid',
      picture: camiseta_atletico_madrid,
      precio_venta: 390,
      descripcion: 'Compra Protegida, recibe el producto que esperabas o te devolvemos tu dinero.',
      marca: 'Adidas',
      stock: 6,
    },
    {
      idproducto: 3,
      nombre: 'Camiseta Barcelona',
      picture: camiseta_barcelona,
      precio_venta: 189,
      descripcion: 'Compra Protegida, recibe el producto que esperabas o te devolvemos tu dinero.',
      marca: 'Nike',
      stock: 2,
    },
    {
      idproducto: 4,
      nombre: 'Camiseta Barcelona antes del mundial',
      picture: camiseta_antes,
      precio_venta: 780,
      descripcion: 'Compra Protegida, recibe el producto que esperabas o te devolvemos tu dinero.',
      marca: 'Nike',
      stock: 6,
    },
    {
      idproducto: 5,
      nombre: 'Camiseta de entrenamiento real madrid',
      picture: camiseta_de_entrenamiento,
      precio_venta: 328,
      marca: 'Nike',
      stock: 10,
    },
    {
      idproducto: 6,
      nombre: 'Camiseta blanca autentico madrid',
      picture: camiseta_blanca_authentic_real_madrid,
      precio_venta: 2733,
      marca: 'Adidas',
      stock: 4,
    } 
  ];